# Site settings
name: Phillip Wang
title: Phillip Wang | Personal Website
description: A sophomore pursuing Bachelor's degree in Computer Science @ NYU Abu Dhabi, into data science, machine learning, and entreprenuership
url: https://phillipw.info/
baseurl: ''
email: hncswpy@gmail.com
cover: https://phillipw.info/img/og.png
logo: https://phillipw.info/img/emojis/technologist.png
resume: https://phillipw.info/resume.pdf
social:
  - title: email
    url: mailto:hncswpy@gmail.com
  - title: twitter
    url: https://twitter.com/hncswpy
  - title: github
    url: https://github.com/cswpy
  - title: linkedin
    url: https://www.linkedin.com/in/pengyu-wang

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
